application: beat-ielts-vocabluary
version: 1
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "5d"

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static
  static_dir: application/static

- url: .*
  script: run.application.app

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"

builtins:
- remote_api: on
- appstats: on